// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //evan big stoopid

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuBu-N1vyDiFROqGpPwknv2fZY4JNO-xk',
    appId: '1:193724399621:web:4f4c851fcd395bd3cbdc6c',
    messagingSenderId: '193724399621',
    projectId: 'men-health-app',
    authDomain: 'men-health-app.firebaseapp.com',
    databaseURL: 'https://men-health-app-default-rtdb.firebaseio.com',
    storageBucket: 'men-health-app.appspot.com',
    measurementId: 'G-E4Y8KT71NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEwVJ-VpIkCE1AESmsxbEAeO0u6uVEGyc',
    appId: '1:193724399621:android:20b0971c9af7854dcbdc6c',
    messagingSenderId: '193724399621',
    projectId: 'men-health-app',
    databaseURL: 'https://men-health-app-default-rtdb.firebaseio.com',
    storageBucket: 'men-health-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBtEIHlYzyOtBOIjKMaePHpY5rrG8FC8',
    appId: '1:193724399621:ios:5bb0f00bdb648ccbcbdc6c',
    messagingSenderId: '193724399621',
    projectId: 'men-health-app',
    databaseURL: 'https://men-health-app-default-rtdb.firebaseio.com',
    storageBucket: 'men-health-app.appspot.com',
    androidClientId:
        '193724399621-fghd6m87a2uncheai1jpsbscbpvsthga.apps.googleusercontent.com',
    iosClientId:
        '193724399621-eo2buoo1b1da4v0fqv5k0dicj84oal66.apps.googleusercontent.com',
    iosBundleId: 'com.example.mensHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDBtEIHlYzyOtBOIjKMaePHpY5rrG8FC8',
    appId: '1:193724399621:ios:5bb0f00bdb648ccbcbdc6c',
    messagingSenderId: '193724399621',
    projectId: 'men-health-app',
    databaseURL: 'https://men-health-app-default-rtdb.firebaseio.com',
    storageBucket: 'men-health-app.appspot.com',
    androidClientId:
        '193724399621-fghd6m87a2uncheai1jpsbscbpvsthga.apps.googleusercontent.com',
    iosClientId:
        '193724399621-eo2buoo1b1da4v0fqv5k0dicj84oal66.apps.googleusercontent.com',
    iosBundleId: 'com.example.mensHealthApp',
  );
}
